name: nigtlytool linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_hash: ${{ steps.build.outputs.commit_hash }}

    steps:
      - uses: actions/checkout@v2

      - name: set up
        run: |
          sudo apt update
          sudo apt install g++

      - name: build
        id: build
        run: |
          g++ nightlytool.cpp -o nightlytool
          mkdir -p ~/artifacts
          cp nightlytool ~/artifacts
          echo ::set-output name=commit_tag::$(git describe --abbrev=0 --tags)
          echo ::set-output name=commit_hash::$(git log --format=%h -1)
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: ubuntu
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on Windows
        shell: bash
        run: g++ nightlytool.cpp -o nightlytool.exe
      - name: "Publish build to GH Actions"
        uses: actions/upload-artifact@v2
        with:
          path: nightlytool.exe
          name: "windows"
  publish_build:
    runs-on: ubuntu-latest
    name: Publish build to NPI-D7/nightlys
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: build windows
    env:
      COMMIT_TAG: ${{ needs.build.outputs.commit_tag }}
      COMMIT_HASH: ${{ needs.build.outputs.commit_hash }}
    outputs:
      current_date: ${{ steps.commit.outputs.current_date }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ubuntu
          path: ubuntu

      - name: Commit and push to NPI-D7/nightlys
        id: commit
        run: |
          CURRENT_DATE=$(date +"%Y%m%d-%H%M%S")
          echo ::set-output name=current_date::$CURRENT_DATE
          git config --global user.email "tobid7@outlook.de"
          git config --global user.name "Tobi-D7"
          git clone --depth 1 https://${{ secrets.TOKEN }}@github.com/NPI-D7/nightlys.git
          cd nightlys
          cp ${{ github.workspace }}/*/* .
          git stage .
          git commit -m "nightlytool | $COMMIT_HASH"
          git tag v$CURRENT_DATE
          git push origin master v$CURRENT_DATE
