name: nigtlytool linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_hash: ${{ steps.build.outputs.commit_hash }}

    steps:
      - uses: actions/checkout@v2

      - name: set up
        run: |
          sudo apt update
          sudo apt install g++ cmake

      - name: build
        id: build
        run: |
          cmake . -B build
          cmake --build build -j4
          mkdir -p ~/artifacts
          cp build/nightlytool ~/artifacts
          echo ::set-output name=commit_tag::$(git describe --abbrev=0 --tags)
          echo ::set-output name=commit_hash::$(git log --format=%h -1)
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: ubuntu